### ISSUE TITLE
Failure creating image when instance is in the powering-off state

### ISSUE THREAD

**Issue by joaompinto** [CCSGroupInternational/osvolbackup#3]
2019-03-08 06:32:18.426963  Creating backup image for server SVR-ADFS-01
Traceback (most recent call last):
  File "/home/stack/.local/bin/osvolbackup", line 10, in <module>
    sys.exit(main())
  File "/home/stack/.local/lib/python2.7/site-packages/osvolbackup/__main__.py", line 16, in main
    cli()
  File "/home/stack/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/stack/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/stack/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stack/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stack/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/stack/.local/lib/python2.7/site-packages/osvolbackup/cli/server.py", line 26, in server
    server.backup(wait=True)
  File "/home/stack/.local/lib/python2.7/site-packages/osvolbackup/server.py", line 85, in backup
    server_backup_image_id = self.instance.create_image(server_backup_name)
  File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 368, in create_image
    return self.manager.create_image(self, image_name, metadata)
  File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1556, in create_image
    body)
  File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 1900, in _action_return_resp_and_body
    return self.api.client.post(url, body=body)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 310, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 83, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.Conflict: Cannot 'createImage' instance b5a178d9-6e0b-4dae-9ba1-8cbafce5517e while it is in task_state powering-off (HTTP 409) (Request-ID: req-463c654c-349f-4ce2-bf0d-13aad924d781)

**Comment by joaompinto** [comment]
There are two options here:
a) Check the VM state and wait for it to become shutdown, during a timeout
b) On error retry the operation for N times, pausing T seconds
